### ISSUE TITLE
Hypervisor error during reinstallation

### ISSUE THREAD

**Issue by g0dd4rd** [kojak/kojak#97]
Description:
This a consequence of the fact that Kojak can't clean up properly even after using the Uninstall option.

Steps to reproduce:
1. fail an installation, for example by reproducing https://github.com/sbadakhc/kojak/issues/96
2. sudo dnf install virt-install
3. re-install Kojak as in https://github.com/sbadakhc/kojak/issues/96 step 2 

Actual results:
ERROR    Disk /var/lib/libvirt/images/kojak-CentOS-6.6-x86_64.img is already in use by other guests ['centos6.5']. (Use --check path_in_use=off or --check all=off to override)

Expected results:
If older VM(s) exist(s), Kojak offers to augment them or creates new one on demand.

**Comment by g0dd4rd** [comment]
workaround: sudo virsh undefine centos6.5 --[remove-all-storage | wipe-storage]

**Comment by sbadakhc** [comment]
Thanks,

Will update and get back to you!
